---
require: rubocop-rake

Metrics/LineLength:
  Exclude:
    - ynab_convert.gemspec

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - ynab_convert.gemspec
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Enabled: false
