---
# See https://github.com/rubocop/rubocop/blob/master/config/default.yml for all
# options
require: rubocop-rake

AllCops:
  DisplayCopNames: true

Metrics/LineLength:
  Exclude:
    - ynab_convert.gemspec

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - ynab_convert.gemspec
    - 'spec/**/*_spec.rb'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Enabled: false
