---
language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.7
  - 3.0
  - 3.1
before_install: gem install bundler

jobs:
  include:
    - stage: test
      script: echo "Running tests for $(ruby -v)..." && bundle exec rake ci
    - stage: gem release
      rvm: 2.6
      script: echo "Publishing to rubygems.org..."
      deploy:
        provider: rubygems
        gem: ynab_convert
        api_key: $RUBYGEMS_API_KEY
        on: master
